apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  selector:
    app: productapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
