apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  selector:
    app: productapi
  ports:
    - protocol: TCP
      port: 80        # Cluster IP port
      targetPort: 80  # Container port (same as in deployment.yaml)
  type: NodePort      # Accessible externally on a high random port (30000–32767)
