name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aspanil04
          password: ${{ secrets.DOCKER_PASSWORD }} # 👈 Store password in GitHub Secrets

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=v1.${{ github.run_number }}
          echo "Image tag: $IMAGE_TAG"
          docker build -t aspanil04/productapi:$IMAGE_TAG .
          docker push aspanil04/productapi:$IMAGE_TAG
        env:
          IMAGE_TAG: v1.${{ github.run_number }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.1

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start

      - name: Set kubectl context to Minikube
        run: kubectl config use-context minikube

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f service.yaml
          kubectl apply -f deployment.yaml

      - name: Update Kubernetes Deployment with Latest Image
        run: |
          IMAGE_TAG=v1.${{ github.run_number }}
          kubectl set image deployment/productapi productapi=aspanil04/productapi:$IMAGE_TAG --record
          kubectl rollout status deployment/productapi
