name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: aspanil04
        password: Monday1234

    - name: Build and push Docker image
      run: |
        docker build -t aspanil04/myapi:v2 .
        docker push aspanil04/myapi:v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
